[package]
name = "atheer-integration-tests"
version.workspace = true
edition.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
atheer-core = { path = "../atheer-core" }
atheer-orchestrator = { path = "../atheer-orchestrator" }
atheer-memory-bank = { path = "../atheer-memory-bank" }

[dev-dependencies]
atheer-ffi = { path = "../atheer-ffi" }
tokio = { version = "1.53", features = ["full"] }
proptest = { workspace = true }
