// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(atheer_ffiFFI)
import atheer_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_atheer_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_atheer_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureAtheerFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AtheerEngineProtocol: AnyObject, Sendable {
    
    func crashLogPath()  -> String?
    
    func generateStream(request: GenerationRequest) throws 
    
    func generateSync(request: GenerationRequest) throws  -> GenerationResponse
    
    func initialize() throws 
    
    func isInitialized()  -> Bool
    
    func loadDraft(path: String) throws 
    
    func pollStreamToken()  -> String?
    
    func setMode(mode: AtheerInferenceMode) throws 
    
    func status()  -> EngineStatus
    
    func streamDone()  -> Bool
    
    func unloadDraft() throws 
    
}
open class AtheerEngine: AtheerEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_atheer_ffi_fn_clone_atheerengine(self.handle, $0) }
    }
public convenience init(config: AtheerConfig) {
    let handle =
        try! rustCall() {
    uniffi_atheer_ffi_fn_constructor_atheerengine_new(
        FfiConverterTypeAtheerConfig_lower(config),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_atheer_ffi_fn_free_atheerengine(handle, $0) }
    }

    

    
open func crashLogPath() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_atheer_ffi_fn_method_atheerengine_crash_log_path(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func generateStream(request: GenerationRequest)throws   {try rustCallWithError(FfiConverterTypeAtheerError_lift) {
    uniffi_atheer_ffi_fn_method_atheerengine_generate_stream(
            self.uniffiCloneHandle(),
        FfiConverterTypeGenerationRequest_lower(request),$0
    )
}
}
    
open func generateSync(request: GenerationRequest)throws  -> GenerationResponse  {
    return try  FfiConverterTypeGenerationResponse_lift(try rustCallWithError(FfiConverterTypeAtheerError_lift) {
    uniffi_atheer_ffi_fn_method_atheerengine_generate_sync(
            self.uniffiCloneHandle(),
        FfiConverterTypeGenerationRequest_lower(request),$0
    )
})
}
    
open func initialize()throws   {try rustCallWithError(FfiConverterTypeAtheerError_lift) {
    uniffi_atheer_ffi_fn_method_atheerengine_initialize(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func isInitialized() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_atheer_ffi_fn_method_atheerengine_is_initialized(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func loadDraft(path: String)throws   {try rustCallWithError(FfiConverterTypeAtheerError_lift) {
    uniffi_atheer_ffi_fn_method_atheerengine_load_draft(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(path),$0
    )
}
}
    
open func pollStreamToken() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_atheer_ffi_fn_method_atheerengine_poll_stream_token(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func setMode(mode: AtheerInferenceMode)throws   {try rustCallWithError(FfiConverterTypeAtheerError_lift) {
    uniffi_atheer_ffi_fn_method_atheerengine_set_mode(
            self.uniffiCloneHandle(),
        FfiConverterTypeAtheerInferenceMode_lower(mode),$0
    )
}
}
    
open func status() -> EngineStatus  {
    return try!  FfiConverterTypeEngineStatus_lift(try! rustCall() {
    uniffi_atheer_ffi_fn_method_atheerengine_status(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func streamDone() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_atheer_ffi_fn_method_atheerengine_stream_done(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func unloadDraft()throws   {try rustCallWithError(FfiConverterTypeAtheerError_lift) {
    uniffi_atheer_ffi_fn_method_atheerengine_unload_draft(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAtheerEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AtheerEngine

    public static func lift(_ handle: UInt64) throws -> AtheerEngine {
        return AtheerEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AtheerEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AtheerEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AtheerEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerEngine_lift(_ handle: UInt64) throws -> AtheerEngine {
    return try FfiConverterTypeAtheerEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerEngine_lower(_ value: AtheerEngine) -> UInt64 {
    return FfiConverterTypeAtheerEngine.lower(value)
}




public struct AtheerConfig: Equatable, Hashable {
    public var modelPath: String?
    public var modelId: String?
    public var draftModelPath: String?
    public var adaptive: Bool
    public var maxTokens: UInt32
    public var temperature: Float
    public var quantization: String
    public var adaptiveHandoff: Bool
    public var memoryBankSizeMb: UInt32
    public var standbyDraftPath: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(modelPath: String?, modelId: String?, draftModelPath: String?, adaptive: Bool, maxTokens: UInt32, temperature: Float, quantization: String, adaptiveHandoff: Bool, memoryBankSizeMb: UInt32, standbyDraftPath: String?) {
        self.modelPath = modelPath
        self.modelId = modelId
        self.draftModelPath = draftModelPath
        self.adaptive = adaptive
        self.maxTokens = maxTokens
        self.temperature = temperature
        self.quantization = quantization
        self.adaptiveHandoff = adaptiveHandoff
        self.memoryBankSizeMb = memoryBankSizeMb
        self.standbyDraftPath = standbyDraftPath
    }

    

    
}

#if compiler(>=6)
extension AtheerConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAtheerConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AtheerConfig {
        return
            try AtheerConfig(
                modelPath: FfiConverterOptionString.read(from: &buf), 
                modelId: FfiConverterOptionString.read(from: &buf), 
                draftModelPath: FfiConverterOptionString.read(from: &buf), 
                adaptive: FfiConverterBool.read(from: &buf), 
                maxTokens: FfiConverterUInt32.read(from: &buf), 
                temperature: FfiConverterFloat.read(from: &buf), 
                quantization: FfiConverterString.read(from: &buf), 
                adaptiveHandoff: FfiConverterBool.read(from: &buf), 
                memoryBankSizeMb: FfiConverterUInt32.read(from: &buf), 
                standbyDraftPath: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: AtheerConfig, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.modelPath, into: &buf)
        FfiConverterOptionString.write(value.modelId, into: &buf)
        FfiConverterOptionString.write(value.draftModelPath, into: &buf)
        FfiConverterBool.write(value.adaptive, into: &buf)
        FfiConverterUInt32.write(value.maxTokens, into: &buf)
        FfiConverterFloat.write(value.temperature, into: &buf)
        FfiConverterString.write(value.quantization, into: &buf)
        FfiConverterBool.write(value.adaptiveHandoff, into: &buf)
        FfiConverterUInt32.write(value.memoryBankSizeMb, into: &buf)
        FfiConverterOptionString.write(value.standbyDraftPath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerConfig_lift(_ buf: RustBuffer) throws -> AtheerConfig {
    return try FfiConverterTypeAtheerConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerConfig_lower(_ value: AtheerConfig) -> RustBuffer {
    return FfiConverterTypeAtheerConfig.lower(value)
}


public struct EngineStatus: Equatable, Hashable {
    public var mode: String
    public var tokensPerSecond: Float
    public var draftLoaded: Bool
    public var hardwareHealth: HardwareHealth
    public var memoryBank: MemoryBankStatus

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(mode: String, tokensPerSecond: Float, draftLoaded: Bool, hardwareHealth: HardwareHealth, memoryBank: MemoryBankStatus) {
        self.mode = mode
        self.tokensPerSecond = tokensPerSecond
        self.draftLoaded = draftLoaded
        self.hardwareHealth = hardwareHealth
        self.memoryBank = memoryBank
    }

    

    
}

#if compiler(>=6)
extension EngineStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineStatus {
        return
            try EngineStatus(
                mode: FfiConverterString.read(from: &buf), 
                tokensPerSecond: FfiConverterFloat.read(from: &buf), 
                draftLoaded: FfiConverterBool.read(from: &buf), 
                hardwareHealth: FfiConverterTypeHardwareHealth.read(from: &buf), 
                memoryBank: FfiConverterTypeMemoryBankStatus.read(from: &buf)
        )
    }

    public static func write(_ value: EngineStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.mode, into: &buf)
        FfiConverterFloat.write(value.tokensPerSecond, into: &buf)
        FfiConverterBool.write(value.draftLoaded, into: &buf)
        FfiConverterTypeHardwareHealth.write(value.hardwareHealth, into: &buf)
        FfiConverterTypeMemoryBankStatus.write(value.memoryBank, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineStatus_lift(_ buf: RustBuffer) throws -> EngineStatus {
    return try FfiConverterTypeEngineStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineStatus_lower(_ value: EngineStatus) -> RustBuffer {
    return FfiConverterTypeEngineStatus.lower(value)
}


public struct GenerationRequest: Equatable, Hashable {
    public var prompt: String
    public var maxTokens: UInt32
    public var temperature: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(prompt: String, maxTokens: UInt32, temperature: Float) {
        self.prompt = prompt
        self.maxTokens = maxTokens
        self.temperature = temperature
    }

    

    
}

#if compiler(>=6)
extension GenerationRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGenerationRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GenerationRequest {
        return
            try GenerationRequest(
                prompt: FfiConverterString.read(from: &buf), 
                maxTokens: FfiConverterUInt32.read(from: &buf), 
                temperature: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: GenerationRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.prompt, into: &buf)
        FfiConverterUInt32.write(value.maxTokens, into: &buf)
        FfiConverterFloat.write(value.temperature, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerationRequest_lift(_ buf: RustBuffer) throws -> GenerationRequest {
    return try FfiConverterTypeGenerationRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerationRequest_lower(_ value: GenerationRequest) -> RustBuffer {
    return FfiConverterTypeGenerationRequest.lower(value)
}


public struct GenerationResponse: Equatable, Hashable {
    public var text: String
    public var tokensGenerated: UInt32
    public var inferenceTimeMs: UInt64
    public var mode: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, tokensGenerated: UInt32, inferenceTimeMs: UInt64, mode: String) {
        self.text = text
        self.tokensGenerated = tokensGenerated
        self.inferenceTimeMs = inferenceTimeMs
        self.mode = mode
    }

    

    
}

#if compiler(>=6)
extension GenerationResponse: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGenerationResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GenerationResponse {
        return
            try GenerationResponse(
                text: FfiConverterString.read(from: &buf), 
                tokensGenerated: FfiConverterUInt32.read(from: &buf), 
                inferenceTimeMs: FfiConverterUInt64.read(from: &buf), 
                mode: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: GenerationResponse, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterUInt32.write(value.tokensGenerated, into: &buf)
        FfiConverterUInt64.write(value.inferenceTimeMs, into: &buf)
        FfiConverterString.write(value.mode, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerationResponse_lift(_ buf: RustBuffer) throws -> GenerationResponse {
    return try FfiConverterTypeGenerationResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerationResponse_lower(_ value: GenerationResponse) -> RustBuffer {
    return FfiConverterTypeGenerationResponse.lower(value)
}


public struct HardwareHealth: Equatable, Hashable {
    public var thermal: String
    public var availableRamMb: UInt64
    public var batteryLevel: UInt32
    public var onBattery: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(thermal: String, availableRamMb: UInt64, batteryLevel: UInt32, onBattery: Bool) {
        self.thermal = thermal
        self.availableRamMb = availableRamMb
        self.batteryLevel = batteryLevel
        self.onBattery = onBattery
    }

    

    
}

#if compiler(>=6)
extension HardwareHealth: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHardwareHealth: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HardwareHealth {
        return
            try HardwareHealth(
                thermal: FfiConverterString.read(from: &buf), 
                availableRamMb: FfiConverterUInt64.read(from: &buf), 
                batteryLevel: FfiConverterUInt32.read(from: &buf), 
                onBattery: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: HardwareHealth, into buf: inout [UInt8]) {
        FfiConverterString.write(value.thermal, into: &buf)
        FfiConverterUInt64.write(value.availableRamMb, into: &buf)
        FfiConverterUInt32.write(value.batteryLevel, into: &buf)
        FfiConverterBool.write(value.onBattery, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHardwareHealth_lift(_ buf: RustBuffer) throws -> HardwareHealth {
    return try FfiConverterTypeHardwareHealth.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHardwareHealth_lower(_ value: HardwareHealth) -> RustBuffer {
    return FfiConverterTypeHardwareHealth.lower(value)
}


public struct MemoryBankStatus: Equatable, Hashable {
    public var l1Active: String?
    public var l2Warm: String?
    public var alignmentScore: Float
    public var isHandoff: Bool
    public var handoffPhase: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(l1Active: String?, l2Warm: String?, alignmentScore: Float, isHandoff: Bool, handoffPhase: String) {
        self.l1Active = l1Active
        self.l2Warm = l2Warm
        self.alignmentScore = alignmentScore
        self.isHandoff = isHandoff
        self.handoffPhase = handoffPhase
    }

    

    
}

#if compiler(>=6)
extension MemoryBankStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMemoryBankStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MemoryBankStatus {
        return
            try MemoryBankStatus(
                l1Active: FfiConverterOptionString.read(from: &buf), 
                l2Warm: FfiConverterOptionString.read(from: &buf), 
                alignmentScore: FfiConverterFloat.read(from: &buf), 
                isHandoff: FfiConverterBool.read(from: &buf), 
                handoffPhase: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MemoryBankStatus, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.l1Active, into: &buf)
        FfiConverterOptionString.write(value.l2Warm, into: &buf)
        FfiConverterFloat.write(value.alignmentScore, into: &buf)
        FfiConverterBool.write(value.isHandoff, into: &buf)
        FfiConverterString.write(value.handoffPhase, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemoryBankStatus_lift(_ buf: RustBuffer) throws -> MemoryBankStatus {
    return try FfiConverterTypeMemoryBankStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMemoryBankStatus_lower(_ value: MemoryBankStatus) -> RustBuffer {
    return FfiConverterTypeMemoryBankStatus.lower(value)
}


public enum AtheerError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case ModelLoadFailed(message: String
    )
    case TokenizerLoadFailed(message: String
    )
    case GenerationFailed(message: String
    )
    case InvalidParameters(message: String
    )
    case NotInitialized
    case InvalidMode(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension AtheerError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAtheerError: FfiConverterRustBuffer {
    typealias SwiftType = AtheerError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AtheerError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ModelLoadFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .TokenizerLoadFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .GenerationFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidParameters(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .NotInitialized
        case 6: return .InvalidMode(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AtheerError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ModelLoadFailed(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .TokenizerLoadFailed(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .GenerationFailed(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidParameters(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case .NotInitialized:
            writeInt(&buf, Int32(5))
        
        
        case let .InvalidMode(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerError_lift(_ buf: RustBuffer) throws -> AtheerError {
    return try FfiConverterTypeAtheerError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerError_lower(_ value: AtheerError) -> RustBuffer {
    return FfiConverterTypeAtheerError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AtheerInferenceMode: Equatable, Hashable {
    
    case turbo
    case balanced
    case eco





}

#if compiler(>=6)
extension AtheerInferenceMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAtheerInferenceMode: FfiConverterRustBuffer {
    typealias SwiftType = AtheerInferenceMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AtheerInferenceMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .turbo
        
        case 2: return .balanced
        
        case 3: return .eco
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AtheerInferenceMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .turbo:
            writeInt(&buf, Int32(1))
        
        
        case .balanced:
            writeInt(&buf, Int32(2))
        
        
        case .eco:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerInferenceMode_lift(_ buf: RustBuffer) throws -> AtheerInferenceMode {
    return try FfiConverterTypeAtheerInferenceMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerInferenceMode_lower(_ value: AtheerInferenceMode) -> RustBuffer {
    return FfiConverterTypeAtheerInferenceMode.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AtheerThermalState: Equatable, Hashable {
    
    case nominal
    case fair
    case serious
    case critical





}

#if compiler(>=6)
extension AtheerThermalState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAtheerThermalState: FfiConverterRustBuffer {
    typealias SwiftType = AtheerThermalState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AtheerThermalState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .nominal
        
        case 2: return .fair
        
        case 3: return .serious
        
        case 4: return .critical
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AtheerThermalState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .nominal:
            writeInt(&buf, Int32(1))
        
        
        case .fair:
            writeInt(&buf, Int32(2))
        
        
        case .serious:
            writeInt(&buf, Int32(3))
        
        
        case .critical:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerThermalState_lift(_ buf: RustBuffer) throws -> AtheerThermalState {
    return try FfiConverterTypeAtheerThermalState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAtheerThermalState_lower(_ value: AtheerThermalState) -> RustBuffer {
    return FfiConverterTypeAtheerThermalState.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_atheer_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_crash_log_path() != 8200) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_generate_stream() != 24474) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_generate_sync() != 54248) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_initialize() != 44585) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_is_initialized() != 58606) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_load_draft() != 37769) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_poll_stream_token() != 5136) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_set_mode() != 57912) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_status() != 34605) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_stream_done() != 16552) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_method_atheerengine_unload_draft() != 38063) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_atheer_ffi_checksum_constructor_atheerengine_new() != 13467) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureAtheerFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all